/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistryIndexRouteImport } from './routes/registry.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as RegistryNameRouteImport } from './routes/registry.$name'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryIndexRoute = RegistryIndexRouteImport.update({
  id: '/registry/',
  path: '/registry/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryNameRoute = RegistryNameRouteImport.update({
  id: '/registry/$name',
  path: '/registry/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/registry/$name': typeof RegistryNameRoute
  '/blog/': typeof BlogIndexRoute
  '/registry/': typeof RegistryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/registry/$name': typeof RegistryNameRoute
  '/blog': typeof BlogIndexRoute
  '/registry': typeof RegistryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/registry/$name': typeof RegistryNameRoute
  '/blog/': typeof BlogIndexRoute
  '/registry/': typeof RegistryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog/$slug' | '/registry/$name' | '/blog/' | '/registry/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog/$slug' | '/registry/$name' | '/blog' | '/registry'
  id:
    | '__root__'
    | '/'
    | '/blog/$slug'
    | '/registry/$name'
    | '/blog/'
    | '/registry/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogSlugRoute: typeof BlogSlugRoute
  RegistryNameRoute: typeof RegistryNameRoute
  BlogIndexRoute: typeof BlogIndexRoute
  RegistryIndexRoute: typeof RegistryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/': {
      id: '/registry/'
      path: '/registry'
      fullPath: '/registry/'
      preLoaderRoute: typeof RegistryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/$name': {
      id: '/registry/$name'
      path: '/registry/$name'
      fullPath: '/registry/$name'
      preLoaderRoute: typeof RegistryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogSlugRoute: BlogSlugRoute,
  RegistryNameRoute: RegistryNameRoute,
  BlogIndexRoute: BlogIndexRoute,
  RegistryIndexRoute: RegistryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()


